# Generated by Django 4.0.5 on 2022-06-15 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='file_url',
            new_name='file',
        ),
    ]
