# Generated by Django 4.0.5 on 2022-06-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
