# Generated by Django 4.0.5 on 2022-06-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_alter_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isRecalled',
            field=models.BooleanField(default=False),
        ),
    ]
